server:
  port: 8080
  servlet:
    context-path: /alx-booking
    
spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/alx-flight-reservation
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    hikari:
      minimumIdle: 5
      maximumPoolSize: 20
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
  flyway:
    table: flyway_scripts
    enabled: true